/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;


import javax.swing.JOptionPane;
import java.io.BufferedOutputStream;
import java.io.OutputStream;
import java.nio.file.Files;
import static java.nio.file.StandardOpenOption.TRUNCATE_EXISTING;
import static java.nio.file.StandardOpenOption.WRITE;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static src.Welcome.driver;
import static src.Welcome.password;
import static src.Welcome.url;
import static src.Welcome.username;

/**
 *
 * @author Anzhe Meng U50590533
 */
public class Sign_up_Dialog extends javax.swing.JDialog {

    /**
     * Creates new form Sign_up_Dialog
     */
    public Sign_up_Dialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lastnameField = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        firstnameField = new javax.swing.JTextField();
        pw2Field = new javax.swing.JPasswordField();
        pwField = new javax.swing.JPasswordField();
        cancelButton = new javax.swing.JButton();
        confirmButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sign up an account");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel2.setText("Please provide your information below.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 40));

        jLabel3.setText("Password again");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 120, 30));

        jLabel4.setText("Username");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, 30));

        jLabel5.setText("First Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 80, 30));

        jLabel6.setText("Last Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 80, 30));

        jLabel7.setText("Password");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 80, 30));
        jPanel1.add(lastnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 210, -1));
        jPanel1.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 210, -1));
        jPanel1.add(firstnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 210, -1));
        jPanel1.add(pw2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 210, -1));
        jPanel1.add(pwField, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 210, 210, -1));

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 90, -1));

        confirmButton1.setText("Confirm");
        confirmButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(confirmButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void confirmButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButton1ActionPerformed
        // TODO add your handling code here:
        String pw1 = new String(pwField.getPassword());
        String pw2 = new String(pw2Field.getPassword());
        
        if (pw1.equals(pw2)) {
            Client client = new Client(usernameField.getText(), firstnameField.getText(), lastnameField.getText(), pw1, Welcome.bank);
            Account account = new Account("Checking", client, Welcome.bank);
            client.addAccount(account);
            Welcome.bank.addAccount(account);
            this.save(client);
            Client_Login.client = client;
            new Client_Menu().setVisible(true);
        }
        else {
            JOptionPane.showConfirmDialog(null, "Your passwords input do not match with each other! Please try again");
        }
    }//GEN-LAST:event_confirmButton1ActionPerformed

    private void save(Client client) {
        String s1 = "";
        String s2 = "";
        String s3 = "";
        s1 += "INSERT INTO Client VALUES(" + 
                client.getID() + "," + client.getUsername() + "," +
                client.getFirstName() + "," + client.getLastName() + 
                "," + client.getPassword() + ");";
        s2 += "INSERT INTO Client_Owned_Account(" + client.getID();
        for (Account a: client.getAccounts()) {
            s2 += "," + a.getID() + "," + a.getName();
        }
        s2 += ");";
        s3 += "INSERT INTO Account(";
        for (Account a: client.getAccounts()) {
            s3 += a.getID();
            for (int i = 0; i < a.getBalance().length; i++) {
                s3 += "." + Double.toString(a.getBalance()[i]) + ");";
            }
        }
         try {
            Class.forName(Welcome.driver);
            Connection conn = DriverManager.getConnection(Welcome.url, Welcome.username, Welcome.password);
            Statement statement = conn.createStatement();
            if (statement.executeLargeUpdate(s1) == 0) {
                JOptionPane.showMessageDialog(null, "Successfully update table Client!");
            }
            if (statement.executeLargeUpdate(s2) == 0) {
                JOptionPane.showMessageDialog(null, "Successfully update table Client_Owned_Account");
            }
            if (statement.executeLargeUpdate(s3) == 0) {
                JOptionPane.showMessageDialog(null, "Successfully update table Account");
            }
            statement.close();
            conn.close();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_up_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_up_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_up_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_up_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Sign_up_Dialog dialog = new Sign_up_Dialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton1;
    private javax.swing.JTextField firstnameField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastnameField;
    private javax.swing.JPasswordField pw2Field;
    private javax.swing.JPasswordField pwField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
